# Generated by Django 3.1.2 on 2022-02-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220210_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={'ordering': ('is_main', 'tag__name'), 'verbose_name': 'Раздел'},
        ),
    ]
