# Generated by Django 3.1.2 on 2022-02-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220210_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescope',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ('tags__is_main', 'name'), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
