# Generated by Django 3.1.2 on 2022-02-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220210_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['scopes'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
